export { IFS } from 'unionfs/lib/fs'

export * from './create'
export * from './copy'
export * from './describe'
export * from './compare'
export * from './visit'
export * from './find'
export * from './match'
export * from './json'
export { toBSON, fromBSON } from './bson'
